Param(
  [switch]$SkipFrontend,
  [switch]$SkipBackend,
  [switch]$RunDiagnostics,
  [switch]$SkipEnvSetup,
  [switch]$ValidateConfig
)

$ErrorActionPreference = 'Stop'

function Assert-Command($name, $hint) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    Write-Host "Missing required command: $name" -ForegroundColor Red
    Write-Host $hint -ForegroundColor Yellow
    exit 1
  }
}

function Read-UserInput($prompt, $default, [switch]$IsPassword) {
  if ($IsPassword) {
    $secureInput = Read-Host -Prompt "$prompt (default: $default)" -AsSecureString
    $plainText = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
      [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureInput)
    )
    if ([string]::IsNullOrWhiteSpace($plainText)) {
      return $default
    }
    return $plainText
  } else {
    $input = Read-Host -Prompt "$prompt (default: $default)"
    if ([string]::IsNullOrWhiteSpace($input)) {
      return $default
    }
    return $input
  }
}

function Setup-EnvFile($backendPath) {
  $envFile = Join-Path $backendPath ".env"
  $envExample = Join-Path $backendPath ".env.example"
  
  if (Test-Path $envFile) {
    Write-Host ".env file already exists at $envFile" -ForegroundColor Yellow
    $overwrite = Read-Host -Prompt "Do you want to reconfigure it? (y/N)"
    if ($overwrite -ne 'y' -and $overwrite -ne 'Y') {
      Write-Host "Keeping existing .env file." -ForegroundColor Green
      return
    }
  }
  
  Write-Host "`n========================================" -ForegroundColor Cyan
  Write-Host "  GraphTrace Environment Configuration" -ForegroundColor Cyan
  Write-Host "========================================" -ForegroundColor Cyan
  Write-Host "Press Enter to accept defaults shown in parentheses.`n" -ForegroundColor Gray
  
  # Database Configuration
  Write-Host "`n--- Database Configuration ---" -ForegroundColor Yellow
  $postgresHost = Read-UserInput "PostgreSQL Host" "localhost"
  $postgresPort = Read-UserInput "PostgreSQL Port" "5433"
  $postgresDb = Read-UserInput "PostgreSQL Database Name" "graphtrace"
  $postgresUser = Read-UserInput "PostgreSQL Username" "postgres"
  $postgresPassword = Read-UserInput "PostgreSQL Password" "tcs12345" -IsPassword
  
  # Neo4j Configuration (Optional)
  Write-Host "`n--- Neo4j Configuration (Optional - press Enter for defaults) ---" -ForegroundColor Yellow
  $neo4jUri = Read-UserInput "Neo4j URI" "neo4j://127.0.0.1:7687"
  $neo4jUser = Read-UserInput "Neo4j Username" "neo4j"
  $neo4jPassword = Read-UserInput "Neo4j Password" "tcs12345" -IsPassword
  $neo4jDatabase = Read-UserInput "Neo4j Database" "neo4j"
  
  # OpenSearch Configuration (Optional)
  Write-Host "`n--- OpenSearch Configuration (Optional - press Enter for defaults) ---" -ForegroundColor Yellow
  $opensearchUrl = Read-UserInput "OpenSearch URL" "http://127.0.0.1:9200"
  $opensearchUser = Read-UserInput "OpenSearch Username (leave empty if no auth)" ""
  $opensearchPassword = ""
  if ($opensearchUser) {
    $opensearchPassword = Read-UserInput "OpenSearch Password" "" -IsPassword
  }
  
  # LLM Configuration (Optional)
  Write-Host "`n--- LLM/AI Configuration (Optional - press Enter to skip) ---" -ForegroundColor Yellow
  $llmProvider = Read-UserInput "LLM Provider (openai/azure_openai/ollama)" ""
  $openaiApiKey = ""
  $azureOpenaiEndpoint = ""
  $azureOpenaiKey = ""
  $azureOpenaiDeployment = ""
  $ollamaHost = ""
  
  if ($llmProvider -eq "openai") {
    $openaiApiKey = Read-UserInput "OpenAI API Key" "" -IsPassword
  } elseif ($llmProvider -eq "azure_openai") {
    $azureOpenaiEndpoint = Read-UserInput "Azure OpenAI Endpoint" ""
    $azureOpenaiKey = Read-UserInput "Azure OpenAI API Key" "" -IsPassword
    $azureOpenaiDeployment = Read-UserInput "Azure OpenAI Deployment Name" "gpt-4"
  } elseif ($llmProvider -eq "ollama") {
    $ollamaHost = Read-UserInput "Ollama Host" "http://localhost:11434"
  }
  
  # Build .env content
  $envContent = @"
# ============================================================================
# GraphTrace Configuration - Generated by bootstrap.ps1
# Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ============================================================================

# PostgreSQL Configuration (Required)
POSTGRES_HOST=$postgresHost
POSTGRES_PORT=$postgresPort
POSTGRES_DATABASE=$postgresDb
POSTGRES_USER=$postgresUser
POSTGRES_PASSWORD=$postgresPassword

# Neo4j Configuration
NEO4J_URI=$neo4jUri
NEO4J_USER=$neo4jUser
NEO4J_PASSWORD=$neo4jPassword
NEO4J_DATABASE=$neo4jDatabase

# OpenSearch Configuration
OPENSEARCH_URL=$opensearchUrl
OPENSEARCH_USERNAME=$opensearchUser
OPENSEARCH_PASSWORD=$opensearchPassword

# LLM Configuration
LLM_PROVIDER=$llmProvider
"@

  if ($openaiApiKey) {
    $envContent += "`nOPENAI_API_KEY=$openaiApiKey"
  }
  if ($azureOpenaiEndpoint) {
    $envContent += "`nAZURE_OPENAI_ENDPOINT=$azureOpenaiEndpoint"
    $envContent += "`nAZURE_OPENAI_API_KEY=$azureOpenaiKey"
    $envContent += "`nAZURE_OPENAI_DEPLOYMENT=$azureOpenaiDeployment"
  }
  if ($ollamaHost) {
    $envContent += "`nOLLAMA_HOST=$ollamaHost"
  }

  $envContent += @"

# ============================================================================
# Additional Configuration (uncomment and configure as needed)
# ============================================================================
# See .env.example for full list of available options

# File System Configuration
# DATA_ROOT_PATH=./data
# UPLOAD_DIR=./data/uploads
# WATCH_FOLDERS=["./data/watch"]

# MongoDB (Optional)
# MONGODB_URI=mongodb://localhost:27017
# MONGODB_DATABASE=graphtrace

# Redis (Optional)
# REDIS_HOST=localhost
# REDIS_PORT=6379

# OpenSearch Advanced Settings
# OPENSEARCH_TIMEOUT_S=30
# OPENSEARCH_VERIFY_CERTS=true
"@

  # Write the .env file
  Set-Content -Path $envFile -Value $envContent -Encoding UTF8
  
  Write-Host "`n.env file created successfully at: $envFile" -ForegroundColor Green
  Write-Host "You can edit this file later to add more configuration options." -ForegroundColor Gray
  Write-Host "See .env.example for all available options.`n" -ForegroundColor Gray
}

function Validate-Configuration($backendPath) {
  Write-Host "`n========================================" -ForegroundColor Cyan
  Write-Host "  Validating Configuration" -ForegroundColor Cyan
  Write-Host "========================================`n" -ForegroundColor Cyan
  
  $envFile = Join-Path $backendPath ".env"
  $allPassed = $true
  
  # Check .env file exists
  Write-Host "Checking .env file..." -ForegroundColor Yellow
  if (Test-Path $envFile) {
    Write-Host "  [OK] .env file exists" -ForegroundColor Green
  } else {
    Write-Host "  [FAIL] .env file not found at $envFile" -ForegroundColor Red
    Write-Host "         Run: .\bootstrap.ps1 to create it" -ForegroundColor Gray
    $allPassed = $false
  }
  
  # Check PostgreSQL connectivity
  Write-Host "Checking PostgreSQL..." -ForegroundColor Yellow
  $pgService = Get-Service -Name "postgresql*" -ErrorAction SilentlyContinue
  if ($pgService -and $pgService.Status -eq "Running") {
    Write-Host "  [OK] PostgreSQL service is running" -ForegroundColor Green
  } else {
    Write-Host "  [WARN] PostgreSQL service not detected or not running" -ForegroundColor Yellow
    Write-Host "         Check: Get-Service -Name postgresql*" -ForegroundColor Gray
    Write-Host "         Start: Start-Service postgresql-x64-16 (adjust version)" -ForegroundColor Gray
  }
  
  # Check Python venv
  Write-Host "Checking Python environment..." -ForegroundColor Yellow
  $venvPath = Join-Path $backendPath "venv"
  if (Test-Path $venvPath) {
    Write-Host "  [OK] Python virtual environment exists" -ForegroundColor Green
  } else {
    Write-Host "  [WARN] Virtual environment not found" -ForegroundColor Yellow
    Write-Host "         Run: .\bootstrap.ps1 to create it" -ForegroundColor Gray
  }
  
  # Check encryption key
  Write-Host "Checking encryption key..." -ForegroundColor Yellow
  $keyFile = Join-Path $backendPath ".graphtrace.encryption_key"
  if ((Test-Path $keyFile) -or $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY) {
    Write-Host "  [OK] Encryption key configured" -ForegroundColor Green
  } else {
    Write-Host "  [WARN] Encryption key not found" -ForegroundColor Yellow
    Write-Host "         Will be generated on first run" -ForegroundColor Gray
  }
  
  # Test database connection using Python
  Write-Host "Testing database connection..." -ForegroundColor Yellow
  Push-Location $backendPath
  try {
    if (Test-Path "venv") {
      & ".\venv\Scripts\Activate.ps1"
      $env:GRAPH_TRACE_LOAD_DOTENV = "true"
      $dbTest = python -c "from core.db_session import engine; engine.connect(); print('OK')" 2>&1
      if ($dbTest -match "OK") {
        Write-Host "  [OK] Database connection successful" -ForegroundColor Green
      } else {
        Write-Host "  [FAIL] Database connection failed" -ForegroundColor Red
        Write-Host "         Error: $dbTest" -ForegroundColor Gray
        $allPassed = $false
      }
    } else {
      Write-Host "  [SKIP] Cannot test - venv not installed" -ForegroundColor Yellow
    }
  } catch {
    Write-Host "  [FAIL] Database connection test error: $($_.Exception.Message)" -ForegroundColor Red
    $allPassed = $false
  } finally {
    Pop-Location
  }
  
  Write-Host ""
  if ($allPassed) {
    Write-Host "All validations passed!" -ForegroundColor Green
  } else {
    Write-Host "Some validations failed. Review the errors above." -ForegroundColor Yellow
  }
  Write-Host ""
  
  return $allPassed
}

Write-Host "GraphTrace bootstrap (Windows)" -ForegroundColor Green

Assert-Command python "Install Python 3.10+ and ensure it's on PATH."
Assert-Command node "Install Node.js 18+ (includes npm)."
Assert-Command npm "Install Node.js 18+ (includes npm)."

$root = $PSScriptRoot

# Validation-only mode
if ($ValidateConfig) {
  Write-Host "[Validate] Checking configuration..." -ForegroundColor Cyan
  Validate-Configuration "$root\python_backend"
  exit 0
}

# Step 0: Environment Configuration (runs unless explicitly skipped)
if (-not $SkipEnvSetup) {
  Write-Host "[0/3] Environment Configuration" -ForegroundColor Cyan
  Setup-EnvFile "$root\python_backend"
}

if (-not $SkipBackend) {
  Write-Host "[1/3] Backend: venv + deps + DB schema + seed" -ForegroundColor Cyan
  Push-Location "$root\python_backend"
  try {
    # Enable .env file loading for Python scripts
    $env:GRAPH_TRACE_LOAD_DOTENV = "true"

    if (-not (Test-Path "venv")) {
      python -m venv venv
    }
    & ".\venv\Scripts\Activate.ps1"

    python -m pip install --upgrade pip
    python -m pip install -r requirement.txt

    $keyFile = Join-Path (Get-Location) ".graphtrace.encryption_key"
    if (-not $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY) {
      if (Test-Path $keyFile) {
        $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY = (Get-Content $keyFile -Raw).Trim()
        Write-Host "Loaded GRAPH_TRACE_CONFIG_ENCRYPTION_KEY from $keyFile" -ForegroundColor Yellow
      }
    }

    if (-not $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY) {
      $key = $null
      try {
        $key = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>$null
      } catch {
        $key = $null
      }

      if (-not $key -or $LASTEXITCODE -ne 0) {
        Write-Host "cryptography not available yet; installing cryptography..." -ForegroundColor Yellow
        python -m pip install cryptography
        $key = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      }

      if ($key) {
        $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY = "$key".Trim()
        Set-Content -Path $keyFile -Value $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY -Encoding ASCII
        Write-Host "Generated and saved GRAPH_TRACE_CONFIG_ENCRYPTION_KEY to $keyFile" -ForegroundColor Yellow
      } else {
        Write-Host "ERROR: Could not generate GRAPH_TRACE_CONFIG_ENCRYPTION_KEY." -ForegroundColor Red
        Write-Host "Set GRAPH_TRACE_CONFIG_ENCRYPTION_KEY and re-run bootstrap." -ForegroundColor Yellow
        exit 1
      }
    }

    # Initialize database schema and seed required configuration
    Write-Host "Initializing database schema + seeding required defaults..." -ForegroundColor Yellow
    $schemaResult = python -m scripts.install_seeded_schema 2>&1
    if ($LASTEXITCODE -eq 0) {
      Write-Host "Database schema initialized and seeded successfully." -ForegroundColor Green
    } else {
      Write-Host ""
      Write-Host "========================================" -ForegroundColor Red
      Write-Host "  DATABASE INITIALIZATION FAILED" -ForegroundColor Red
      Write-Host "========================================" -ForegroundColor Red
      Write-Host ""
      Write-Host "Error details:" -ForegroundColor Yellow
      Write-Host $schemaResult -ForegroundColor Gray
      Write-Host ""
      Write-Host "TROUBLESHOOTING STEPS:" -ForegroundColor Cyan
      Write-Host ""
      Write-Host "1. Check PostgreSQL is running:" -ForegroundColor White
      Write-Host "   Get-Service -Name postgresql*" -ForegroundColor Gray
      Write-Host "   If not running: Start-Service postgresql-x64-16" -ForegroundColor Gray
      Write-Host ""
      Write-Host "2. Verify database exists:" -ForegroundColor White
      Write-Host "   psql -U postgres -h localhost -c '\l'" -ForegroundColor Gray
      Write-Host "   If missing: psql -U postgres -h localhost -c 'CREATE DATABASE graphtrace;'" -ForegroundColor Gray
      Write-Host ""
      Write-Host "3. Verify credentials in .env file:" -ForegroundColor White
      Write-Host "   notepad python_backend\.env" -ForegroundColor Gray
      Write-Host "   Check POSTGRES_HOST, POSTGRES_PORT, POSTGRES_USER, POSTGRES_PASSWORD" -ForegroundColor Gray
      Write-Host ""
      Write-Host "4. Test connection manually:" -ForegroundColor White
      Write-Host "   psql -U postgres -h localhost -p 5433 -d graphtrace" -ForegroundColor Gray
      Write-Host ""
      Write-Host "5. Re-run bootstrap after fixing:" -ForegroundColor White
      Write-Host "   .\bootstrap.ps1 -SkipEnvSetup" -ForegroundColor Gray
      Write-Host ""
      Write-Host "6. If seeding fails with encryption key errors (common in prod):" -ForegroundColor White
      Write-Host "   Set GRAPH_TRACE_CONFIG_ENCRYPTION_KEY to a stable value and re-run." -ForegroundColor Gray
      Write-Host "   (In production mode, GraphTrace will refuse to seed without an explicit key.)" -ForegroundColor Gray
      Write-Host ""
      Write-Host "For more help, see: docs\reference\SETUP.md" -ForegroundColor Yellow
      Write-Host ""
    }
  }
  finally {
    Pop-Location
  }
}

if (-not $SkipFrontend) {
  Write-Host "[2/3] Frontend: npm install" -ForegroundColor Cyan
  Push-Location "$root\e2etraceapp"
  try {
    npm install
  }
  finally {
    Pop-Location
  }
}

if ($RunDiagnostics) {
  Write-Host "[3/3] Diagnostics" -ForegroundColor Cyan
  & "$root\diagnostics\windows\diagnose-all.ps1"
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Bootstrap Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Start the application:" -ForegroundColor White
Write-Host "   .\start-all.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Or start services individually:" -ForegroundColor White
Write-Host "   .\start-backend.ps1   (API: http://localhost:8011)" -ForegroundColor Gray
Write-Host "   .\start-frontend.ps1  (UI: http://localhost:5173)" -ForegroundColor Gray
Write-Host ""
Write-Host "IF YOU ENCOUNTER ERRORS:" -ForegroundColor Yellow
Write-Host ""
Write-Host "- Database connection failed:" -ForegroundColor White
Write-Host "  1. Ensure PostgreSQL is running: Get-Service postgresql*" -ForegroundColor Gray
Write-Host "  2. Create database if missing: psql -U postgres -c 'CREATE DATABASE graphtrace;'" -ForegroundColor Gray
Write-Host "  3. Verify .env credentials: notepad python_backend\.env" -ForegroundColor Gray
Write-Host ""
Write-Host "- Neo4j connection failed:" -ForegroundColor White
Write-Host "  1. Ensure Neo4j is running (or configure in UI later)" -ForegroundColor Gray
Write-Host "  2. Verify NEO4J_* settings in python_backend\.env" -ForegroundColor Gray
Write-Host ""
Write-Host "- Run diagnostics:" -ForegroundColor White
Write-Host "  .\bootstrap.ps1 -RunDiagnostics" -ForegroundColor Gray
Write-Host ""
Write-Host "- Reconfigure environment:" -ForegroundColor White
Write-Host "  .\bootstrap.ps1 -SkipBackend -SkipFrontend" -ForegroundColor Gray
Write-Host ""
Write-Host "For detailed setup guide: docs\SETUP.md" -ForegroundColor Cyan
Write-Host ""
