version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: graphtrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/neo4jpassword"
      NEO4J_server_memory_pagecache_size: "1G"
      NEO4J_server_memory_heap_initial__size: "1G"
      NEO4J_server_memory_heap_max__size: "1G"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs

  backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/graphtrace"
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "neo4jpassword"
      NEO4J_DATABASE: "neo4j"
      ALLOWED_ORIGINS: "http://localhost:8080"
    depends_on:
      - postgres
      - neo4j
    ports:
      - "8011:8011"

  frontend:
    build:
      context: ./e2etraceapp
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
  neo4jdata:
  neo4jlogs:
