# PowerShell script to start the GraphTrace Python backend
# Usage: .\start-backend.ps1

Write-Host "Starting GraphTrace Backend Server..." -ForegroundColor Green

    # Opt into repo-local `.env` loading for local development.
    if (-not $env:GRAPH_TRACE_LOAD_DOTENV) {
        $env:GRAPH_TRACE_LOAD_DOTENV = "true"
    }

# Check if Python is installed
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    Write-Host "Error: Python is not installed or not in PATH" -ForegroundColor Red
    exit 1
}

# Navigate to backend directory
Set-Location -Path "$PSScriptRoot\python_backend"

# Check if virtual environment exists
if (-not (Test-Path "venv")) {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv venv
}

# Activate virtual environment
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
& ".\venv\Scripts\Activate.ps1"

# Check if .env file exists and offer to create it
if (-not (Test-Path ".env")) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host "  .env file not found!" -ForegroundColor Yellow
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "The .env file is required for database and service configuration." -ForegroundColor Gray
    Write-Host ""
    
    $createEnv = Read-Host -Prompt "Would you like to create .env now? (Y/n)"
    if ($createEnv -ne 'n' -and $createEnv -ne 'N') {
        Write-Host ""
        Write-Host "--- Quick Setup: Enter your configuration ---" -ForegroundColor Cyan
        Write-Host "Press Enter to accept defaults shown in parentheses.`n" -ForegroundColor Gray
        
        # PostgreSQL Configuration
        Write-Host "--- PostgreSQL Database ---" -ForegroundColor Yellow
        $pgHost = Read-Host -Prompt "PostgreSQL Host (localhost)"
        if ([string]::IsNullOrWhiteSpace($pgHost)) { $pgHost = "localhost" }
        
        $pgPort = Read-Host -Prompt "PostgreSQL Port (5433)"
        if ([string]::IsNullOrWhiteSpace($pgPort)) { $pgPort = "5433" }
        
        $pgDb = Read-Host -Prompt "PostgreSQL Database (graphtrace)"
        if ([string]::IsNullOrWhiteSpace($pgDb)) { $pgDb = "graphtrace" }
        
        $pgUser = Read-Host -Prompt "PostgreSQL User (postgres)"
        if ([string]::IsNullOrWhiteSpace($pgUser)) { $pgUser = "postgres" }
        
        $pgPassword = Read-Host -Prompt "PostgreSQL Password (tcs12345)" -AsSecureString
        $pgPasswordPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($pgPassword)
        )
        if ([string]::IsNullOrWhiteSpace($pgPasswordPlain)) { $pgPasswordPlain = "tcs12345" }
        
        # Neo4j Configuration (Optional)
        Write-Host "`n--- Neo4j (Optional - press Enter for defaults) ---" -ForegroundColor Yellow
        $neo4jUri = Read-Host -Prompt "Neo4j URI (neo4j://127.0.0.1:7687)"
        if ([string]::IsNullOrWhiteSpace($neo4jUri)) { $neo4jUri = "neo4j://127.0.0.1:7687" }
        
        $neo4jUser = Read-Host -Prompt "Neo4j User (neo4j)"
        if ([string]::IsNullOrWhiteSpace($neo4jUser)) { $neo4jUser = "neo4j" }
        
        $neo4jPassword = Read-Host -Prompt "Neo4j Password (tcs12345)"
        if ([string]::IsNullOrWhiteSpace($neo4jPassword)) { $neo4jPassword = "tcs12345" }
        
        # OpenSearch Configuration (Optional)
        Write-Host "`n--- OpenSearch (Optional - press Enter for defaults) ---" -ForegroundColor Yellow
        $opensearchUrl = Read-Host -Prompt "OpenSearch URL (http://127.0.0.1:9200)"
        if ([string]::IsNullOrWhiteSpace($opensearchUrl)) { $opensearchUrl = "http://127.0.0.1:9200" }
        
        $opensearchUser = Read-Host -Prompt "OpenSearch Username (leave empty if no auth)"
        $opensearchPassword = ""
        if (-not [string]::IsNullOrWhiteSpace($opensearchUser)) {
            $opensearchPassword = Read-Host -Prompt "OpenSearch Password"
        }
        
        # Create .env file
        $envContent = @"
# ============================================================================
# GraphTrace Configuration - Generated by start-backend.ps1
# Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ============================================================================

# PostgreSQL Configuration (Required)
POSTGRES_HOST=$pgHost
POSTGRES_PORT=$pgPort
POSTGRES_DATABASE=$pgDb
POSTGRES_USER=$pgUser
POSTGRES_PASSWORD=$pgPasswordPlain

# Neo4j Configuration (Optional)
NEO4J_URI=$neo4jUri
NEO4J_USER=$neo4jUser
NEO4J_PASSWORD=$neo4jPassword
NEO4J_DATABASE=neo4j

# OpenSearch Configuration (Optional)
OPENSEARCH_URL=$opensearchUrl
OPENSEARCH_USERNAME=$opensearchUser
OPENSEARCH_PASSWORD=$opensearchPassword

# File System Configuration
# DATA_ROOT_PATH=./data
# WATCH_FOLDERS=["./data/watch"]

# LLM Configuration (uncomment and configure as needed)
# LLM_PROVIDER=openai
# OPENAI_API_KEY=your_api_key

# See .env.example for all available configuration options
"@
        
        Set-Content -Path ".env" -Value $envContent -Encoding UTF8
        Write-Host ""
        Write-Host ".env file created successfully!" -ForegroundColor Green
        Write-Host "You can edit python_backend\.env to add more settings later." -ForegroundColor Gray
        Write-Host ""
    } else {
        Write-Host ""
        Write-Host "Continuing without .env file..." -ForegroundColor Yellow
        Write-Host "Note: You can create .env manually using .env.example as a template." -ForegroundColor Gray
        Write-Host "      Or run .\bootstrap.ps1 to go through the full setup wizard." -ForegroundColor Gray
        Write-Host ""
    }
}

# Install/upgrade dependencies
Write-Host "Installing/updating dependencies..." -ForegroundColor Yellow
python -m pip install --upgrade pip
python -m pip install -r requirement.txt

# Ensure encryption key exists for DB-backed encrypted configuration.
# Check for persisted key file first, then generate if needed.
$keyFile = Join-Path (Get-Location) ".graphtrace.encryption_key"
if (-not $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY) {
    if (Test-Path $keyFile) {
        $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY = (Get-Content $keyFile -Raw).Trim()
        Write-Host "Loaded encryption key from $keyFile" -ForegroundColor Yellow
    } else {
        try {
            $key = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
            $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY = $key.Trim()
            # Persist the key for future sessions
            Set-Content -Path $keyFile -Value $env:GRAPH_TRACE_CONFIG_ENCRYPTION_KEY -Encoding ASCII
            Write-Host "Generated and saved encryption key to $keyFile" -ForegroundColor Yellow
        } catch {
            Write-Host "Warning: could not generate GRAPH_TRACE_CONFIG_ENCRYPTION_KEY (cryptography missing?)." -ForegroundColor Yellow
            Write-Host "Set GRAPH_TRACE_CONFIG_ENCRYPTION_KEY manually for encrypted DB config." -ForegroundColor Yellow
        }
    }
}

# Ensure DB schema exists and seed default configuration.
Write-Host "Initializing database schema and seeding defaults..." -ForegroundColor Yellow
try {
    $schemaOutput = python -m scripts.init_db_schema 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Database schema initialized successfully." -ForegroundColor Green
    } else {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Red
        Write-Host "  DATABASE CONNECTION ERROR" -ForegroundColor Red
        Write-Host "========================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "Could not connect to PostgreSQL database." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Error details:" -ForegroundColor Gray
        Write-Host $schemaOutput -ForegroundColor Gray
        Write-Host ""
        Write-Host "QUICK FIXES:" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "1. Is PostgreSQL running?" -ForegroundColor White
        Write-Host "   > Get-Service -Name postgresql*" -ForegroundColor DarkGray
        Write-Host ""
        Write-Host "2. Does the database exist?" -ForegroundColor White
        Write-Host "   > psql -U postgres -h localhost -c 'CREATE DATABASE graphtrace;'" -ForegroundColor DarkGray
        Write-Host ""
        Write-Host "3. Check your .env credentials:" -ForegroundColor White
        Write-Host "   > notepad .env" -ForegroundColor DarkGray
        Write-Host ""
        Write-Host "4. After fixing, restart this script." -ForegroundColor White
        Write-Host ""
        
        $continue = Read-Host -Prompt "Continue starting server anyway? (y/N)"
        if ($continue -ne 'y' -and $continue -ne 'Y') {
            Write-Host "Exiting. Fix the database connection and try again." -ForegroundColor Yellow
            exit 1
        }
        Write-Host "Continuing without database initialization..." -ForegroundColor Yellow
    }
} catch {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Red
    Write-Host "  DATABASE INITIALIZATION FAILED" -ForegroundColor Red  
    Write-Host "========================================" -ForegroundColor Red
    Write-Host ""
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "This usually means PostgreSQL is not running or .env is misconfigured." -ForegroundColor Yellow
    Write-Host ""
    
    $continue = Read-Host -Prompt "Continue starting server anyway? (y/N)"
    if ($continue -ne 'y' -and $continue -ne 'Y') {
        Write-Host "Exiting. Fix the issue and try again." -ForegroundColor Yellow
        exit 1
    }
    Write-Host "If this is a fresh install, ensure PostgreSQL is running and database exists." -ForegroundColor Gray
}

# Set PYTHONPATH
$env:PYTHONPATH = "$PSScriptRoot\python_backend"

# Start the server
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "Starting FastAPI server on port 8011..." -ForegroundColor Green
Write-Host "API Documentation: http://localhost:8011/docs" -ForegroundColor Cyan
Write-Host "Press Ctrl+C to stop the server" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

python -m uvicorn main:app --host 0.0.0.0 --port 8011 --reload
